--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LuthMC/AFKZone
build-by-default: true
branches:
- main
projects:
  AFKZone:
    path: ""
    icon: icon.png
    libs:
     - src: jojoe77777/FormAPI/libFormAPI
       version: ^2.1.1
       branch: "main"
    depend:
     - src: Ifera/ScoreHud/ScoreHud
       version: 8.0.0
       branch: "main"
...
