name: AFKZone
main: Luthfi\AFKZone\Main
author: Luthfi
version: 2.3.0
api: 5.17.0
depend: ["ScoreHud"]
commands:
  afkzone:
    description: Configure the AFKZone
    usage: /afkzone <ui|setworld|setposition>
    aliases: [az]
    permission: afkzone.command
  settopafk:
    description: Allow to set leaderboard
    permission: afkzone.settopafk
  topafk:
    description: Allow player to see top afk
    permission: afkzone.topafk
permissions:
  afkzone.command:
    description: Allows the player to configure the AFKZone
    default: op
  afkzone.settopafk:
    description: Allows the player to configure the AFKZone Leaderboard
    default: op
  afkzone.topafk:
    description: Allows the player see top afk
    default: true
