# AFKZone Settings

economy-plugin: "BedrockEconomy" # EconomyAPI or BedrockEconomy

afk-zone:
  world: ""
  x1: 0
  y1: 0
  z1: 0
  x2: 0
  y2: 0
  z2: 0

rewards:
  - type: "money"
    amount: 1000
  - type: "item"
    item: "diamond"
    amount: 1
  - type: "command"
    command: "give {player} diamond 1"
